### ISSUE TITLE
Constantly skidmarking when driving backwards

### ISSUE THREAD

**Issue by contrexo** [Nition/UnitySkidmarks#2]
Hi, 
thank you very much for your Skidmark-Code. It really saves me a lot of time.
I've tried it out and it works like a charm, except one little issue.
When my car is driving backwards, it was constantly creating skidmarks.
Am I the only one, who had that problem?

I've solved it for me by adding Mathf.Abs to the "bad wheelCollider physics line".
`wheelSpin = Mathf.Max(0, wheelSpin * (0 - Mathf.Abs(carForwardVel)));`

**Comment by Nition** [comment]
Good find, and good fix thanks. I've now updated the source code to include the Mathf.Abs.

Ideally you'd want to remove that whole line and actually fix the car's wheel physics instead. That default car is _always_ skidding its wheels, which is the real root of the problem. Unfortunately with the current PhysX version in Unity since Unity 5, it's hard to get a good friction setup where your wheels aren't either sliding on ice or jittering all over the place. As evidenced by the fact that even the official car setup from Unity has no grip.

There are a few solutions around. For instance this one implements a custom wheel collider:
https://assetstore.unity.com/packages/tools/physics/universal-wheel-physics-41456
This one uses wheel colliders but ignores the default friction and does its own:
https://assetstore.unity.com/packages/tools/physics/edy-s-vehicle-physics-403

**Comment by contrexo** [comment]
Thank you :)

That's right, the wheels are jittering all the time and i've needed quite some time to figure out a solution (for me) for the grip problem (added downforce, use a high stiffness value and an anti-roll-bar-script from edy (https://www.edy.es/dev/2011/10/the-stabilizer-bars-creating-physically-realistic-stable-vehicles/)).

So it's my first unity project ever and I just wanted to start small, maybe I will use edy's awesome physics in a later project.
